name: Despliegue y Publicación en Producción 
on:
  push:
    branches: [ main ]
jobs:
  deploy_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build en Maven 
      run: mvn package -DskipTests

    - name: Construir y etiquetar imagen Docker
      run: |
        docker build -t myorg/nitflex:${{ github.sha }} .
        docker push myorg/nitflex:${{ github.sha }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push myorg/nitflex:${{ github.sha }}

    - name: Deploy to Azure
      uses: azure/docker-login@v1
      with:
        login-server: mycontainerregistry.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    - run: |
        az webapp create --resource-group myResourceGroup --plan myAppServicePlan --name nitflex --deployment-container-image-name mycontainerregistry.azurecr.io/nitflex:${{ github.sha }}
      
    - name: Run test de sistema
      run: mvn -Dhost=http://xxxxx.azurecontainer.io:8080 -Dtest=SmokeTest#testWelcomeMessage test


#    - name: Run smoke tests
#      env:
#        HOST: ${{ steps.deploy.outputs.application-url }}
#      run: mvn -Dtest=SmokeTest -Dhost=$HOST test
