name: 4 - Pruebas de sistema nocturnas en producción

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest] # macOS para Safari si es necesario en el futuro
        browser: [chrome, firefox, edge] # Safari se omite por incompatibilidad con Windows y Linux
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Browser Environment
        run: |
          if [ "${{ matrix.browser }}" = "chrome" ]; then
            echo "BROWSER=chrome" >> $GITHUB_ENV
          elif [ "${{ matrix.browser }}" = "firefox" ]; then
            echo "BROWSER=firefox" >> $GITHUB_ENV
          elif [ "${{ matrix.browser }}" = "edge" ]; then
            echo "BROWSER=edge" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Run System Tests
        run: mvn test -Dtest=FilmUITest -Dbrowser=${{ env.BROWSER }}
        env:
          HOST: "http://elisacaboymariahaba.h3ffe9c9bsbgemeq.westeurope.azurecontainer.io:8080"

