name: Ejecución de Pruebas Unitarias, Integración y de Sistema
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set up Chrome browser
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'

    - name: Set up ChromeDriver
      uses: browser-actions/setup-chromedriver@v1

    - name: Run test de integracion  
      run: mvn test -Dtest=UrlUtilsIntegrationTest
    - name: Run test unitario
      run: mvn test -Dtest=FilmServiceUnitaryTest
    - name: Run test de sistema
      run: mvn test -Dtest=SmokeTest -Dhost="localhost:8080"
