name: 4 - Pruebas de sistema nocturnas en producción

on:
#  schedule:
#    - cron: '0 0 * * *' 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
        os: ['windows-latest', 'macos-latest', 'ubuntu-latest']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Browser Drivers
        uses: webdriverextensions/install-webdriver@v2
        with:
          browser: ${{ matrix.browser }}
      
      - name: Run system tests on ${{ matrix.browser }} on ${{ matrix.os }}
        run: |
          export HOST="http://elisacaboymariahaba.h3ffe9c9bsbgemeq.westeurope.azurecontainer.io:8080"
          mvn test -Dhost=$HOST -Dbrowser=${{ matrix.browser }} -Dos=${{ matrix.os }} -Dtest=SmokeTest
