name: 3 - Despliegue y Publicación en Producción 

on:
  push:
    branches: [ main ]

# añadido nuevo por diapos
permissions: 
  id-token: write
  contents: read 
# hasta aqui 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        # distribution: 'temurin'
      
    - name: Generate Docker image
      run: mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/anuncios:v1

    - name: Login to DockerHub
      run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

    - name: Push image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/anuncios:v1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Change to project directory
        run: cd path/to/your/project
      
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: 'Run az commands to deploy container'
        run: |
          az container create \
          --resource-group ${{ secrets.AZURE_GROUP }} \
          --name anuncios \
          --image ${{ secrets.DOCKERHUB_USERNAME }}/anuncios:v1 \
          --dns-name-label elisacaboymariahaba \
          --ports 8080

      - name: Run system test
        run: |
          cd ais-e.cabo-m.haba-2024-ghf/pom.xml
          mvn test -Dhost=http://elisacaboymariahaba.h3ffe9c9bsbgemeq.westeurope.azurecontainer.io:8080 -Dtest=SmokeTest
