name: 4 - Pruebas de sistema nocturnas en producción

on:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ['chrome', 'firefox', 'edge', 'safari']
        os: ['windows-latest', 'macos-latest', 'ubuntu-latest']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run system tests on ${{ matrix.browser }} on ${{ matrix.os }}
        run: mvn test -Dhost=http://elisacaboymariahaba.h3ffe9c9bsbgemeq.westeurope.azurecontainer.io:8080 -Dbrowser=${{ matrix.browser }} -Dos=${{ matrix.os }} -Dtest=SmokeTest
        
