name: Pruebas de sistema nocturnas en producción

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        browser: ['chrome', 'firefox', 'edge', 'safari']
        os: 
          - name: windows-latest
            browser_exclude: ['safari']
          - name: macos-latest
            browser_exclude: ['chrome', 'firefox', 'edge']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run system tests on ${{ matrix.browser }} on ${{ matrix.os }}
        run: |
          # Establecer la propiedad del sistema "host"
          export host="http://elisacaboymariahaba.h3ffe9c9bsbgemeq.westeurope.azurecontainer.io:8080"
          mvn test -Dhost=$host -Dbrowser=${{ matrix.browser }} -Dos=${{ matrix.os }} -Dtest=SmokeTest
