name: 4 - Pruebas de sistema nocturnas en producción

on:
  schedule:
  - cron: '0 0 * * *' 

jobs:
  test:
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
      fail-fast: false

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Chrome and ChromeDriver (for Chrome)
        if: matrix.browser == 'chrome'
        run: |
          choco install googlechrome
          choco install chromedriver

      - name: Install Firefox and GeckoDriver (for Firefox)
        if: matrix.browser == 'firefox'
        run: |
          choco install firefox
          choco install selenium-gecko-driver

      - name: Run Smoke Test
        run: |
          mvn test -Dhost="http://elisacaboymariahaba.h3ffe9c9bsbgemeq.westeurope.azurecontainer.io:8080" -Dbrowser=${{ matrix.browser }} -Dtest=SmokeTest

      - name: Run System Tests
        run: mvn test -Dtest=FilmUITest -Dbrowser=${{ env.BROWSER }}
        env:
          HOST: "http://elisacaboymariahaba.h3ffe9c9bsbgemeq.westeurope.azurecontainer.io:8080"
