name: 4 - Pruebas de Sistema Nocturnas en Producción

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        browser: [chrome, firefox, edge, safari]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Browser Environment
        run: |
          if [ "${{ matrix.browser }}" = "safari" ] && [ "${{ matrix.os }}" = "macos-latest" ]; then
            # Setup commands for Safari on macOS
          elif [ "${{ matrix.browser }}" = "edge" ]; then
            # Setup commands for Edge
          elif [ "${{ matrix.browser }}" = "firefox" ]; then
            # Setup commands for Firefox
          elif [ "${{ matrix.browser }}" = "chrome" ]; then
            # Setup commands for Chrome
          fi
        shell: bash

      - name: Run System Tests
        run: |
          mvn test -Dtest=CustomFilmUITest -Dbrowser=${{ matrix.browser }}
        shell: bash
